#Information injected by terraform
projectValues:
  stage: "SET_BY_TERRAFORM"
  traefikElbId: "SET_BY_TERRAFORM"
  rootDomain: "SET_BY_TERRAFORM"

global:
  helm:
    #From which Helm repo the charts should be pulled
    repoURL: https://charts.iits.tech/
    # Default Helm Parameters which are injected into every chart
    parameters:
      ingressRoute.adminDomain: "admin.{{.Values.projectValues.rootDomain}}"

charts:
  argocd-config:
    namespace: argocd
    targetRevision: 0.4.1
    parameters:
      ingressRoute.certificate.enabled: "true"
      ingressRoute.entryPointName: "websecure"

  traefik:
    namespace: routing
    targetRevision: 10.22.0-internal-svc
    # Overrides default Helm Parameters
    parameters:
      "traefik.deployment.replicas": "1"
      "traefik.service.annotations.kubernetes\\.io\\/elb\\.id": "{{.Values.projectValues.traefikElbId}}"

  cert-manager:
    namespace: cert-manager
    targetRevision: 0.2.3
    parameters:
      "clusterIssuer.http.email": "my-mail@mail.com"

  basic-auth-gateway:
    namespace: routing
    targetRevision: 0.5.1
    parameters:
      "ingressRoute.domain": "admin.{{.Values.projectValues.rootDomain}}"
  akhq:
    namespace: kafka
    repoURL: "https://github.com/iits-consulting/otc-infrastructure-charts-template.git"
    targetRevision: "main"
    path: "local-charts/akhq"

